# Site Details
site_name: Haututu Guides
site_description: The (un)official knowledgebase for the Hacklab 
site_author: Dyson Parkes
site_url: https://haututu-hacklab.github.io/Guides/
edit_uri: https://github.com/Haututu-Hacklab/Guides/edit/development/docs/
repo_url: https://github.com/Haututu-Hacklab/Guides
repo_name: Haututu-Hacklab/Guides
copyright: >
  Copyright &copy; 2024 <a href="https://github.com/Haututu-Hacklab/">Haututu Hacklab</a> – <a href="#__consent">Change cookie settings</a>

# Site appearance (logos, colours, icons)
theme:
  name: material
  custom_dir: docs/overrides
  language: en
  code_wrap: true
  features:
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.follow
    - toc.integrate
  favicon: assets/logo/favicon.ico
  logo: assets/logo/haututu.png
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Additional links
extra:
  consent:
    title: Cookie consent
    actions:
      - accept
      - manage
      - reject
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well as to store your site preferences.
      With your consent, you're helping us to make our documentation better (and to work better for you).
  social:
#    - icon: "fontawesome/brands/discord"
#      link: "LINK_NEEDED""
    - icon: "fontawesome/brands/facebook"
      link: "https://www.facebook.com/profile.php?id=100088352556892"


# Extra CSS
extra_css:
  - assets/stylesheets/extra.css

# Markdown extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - meta
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      guess_lang: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.saneheaders
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - sane_lists
  - toc:
      permalink: true
      toc_depth: 5

# mkdocs function extensions
plugins:
  - search
  - git-revision-date-localized:
      type: timeago
      locale: en
      fallback_to_build_date: false
  - git-authors

# Navigation Layout
nav:
  - Home: index.md
  - Getting Started:
    - Membership: info/membership.md
    - Facilities: info/facilities.md
  - Guides:
    - guides/index.md
    - Laser Cutting:
      - Images: guides/laser/images.md
      - Materials: guides/laser/materials.md
      - Speeds: guides/laser/speeds.md
    - 3D Printing:
      - Things to consider: guides/3dprinting/considerations.md
      - Limitations: guides/3dprinting/limitations.md
    - Artificial Intelligence:
      - Making Art with AI: guides/ai/art.md
      - Chatbots and talking with LLMs: guides/ai/chat.md
  - Contributing:
    - Adding to the info: info/addinginfo.md
  - Official Hacklab Site: https://www.haututuhacklab.nz/
